export const projects = [
  {
    title: "Chatix",
    githubHref: "https://github.com/fares-ahmedd/chatix",
    videoHref: "https://www.youtube.com/watch?v=tEBxzoBT2ws",
    liveDemoHref: "https://chatix-steel.vercel.app/",
    imageSrc: "/projects/chatix.png",
    techniques: ["ReactJs", "Firebase", "StyledComponents", "React Router Dom"],
    category: "React",
  },
  {
    title: "MovieNesting",
    githubHref: "https://github.com/fares-ahmedd/movieNesting",
    videoHref: "https://www.youtube.com/watch?v=qFE7opP23QQ",
    liveDemoHref: "https://movie-nesting.netlify.app/",
    imageSrc: "/projects/movieNesting.png",
    techniques: ["ReactJs", "Sass", "Redux Toolkit", "React Router Dom"],
    category: "React",
  },
  {
    title: "SocialLinx",
    githubHref: "https://github.com/fares-ahmedd/socialLinx",
    videoHref: "https://www.youtube.com/watch?v=XAbQJMnJJF0&t=3s",
    liveDemoHref: "https://social-linx.vercel.app/",
    imageSrc: "/projects/socialLinx.png",
    techniques: [
      "ReactJs",
      "Tailwind Css",
      "Appwrite",
      "React Query",
      "Shadcn Ui",
      "React Router Dom",
    ],
    category: "React",
  },
  {
    title: "RoomRover",
    githubHref: "https://github.com/fares-ahmedd/roomRover",
    videoHref: "https://www.youtube.com/watch?v=Ejl4_zKGPU0",
    liveDemoHref: "https://room-rover-bice.vercel.app/",
    imageSrc: "/projects/roomRover.png",
    techniques: ["NextJs", "Tailwind Css", "Clerk", "Stripe", "Supabase"],
    category: "Next",
  },
  {
    title: "MarketKing",
    githubHref: "https://github.com/fares-ahmedd/marketKing-ecommerce",
    videoHref: "https://www.youtube.com/watch?v=VTul_vrNah4&t=30s",
    liveDemoHref: "https://market-king-ecommerce.vercel.app/",
    imageSrc: "/projects/marketking.png",
    techniques: [
      "NextJs",
      "Tailwind Css",
      "Neon",
      "Prisma",
      "Shadcn Ui",
      "Stripe",
    ],
    category: "Next",
  },

  {
    title: "Personal Portfolio",
    githubHref: "https://github.com/fares-ahmedd/my-portfolio",
    videoHref: "https://www.youtube.com/watch?v=MselznSgIW4",
    imageSrc: "/projects/personal-portfolio.png",
    techniques: ["ReactJs", "Framer Motion", "Tailwind Css"],
    category: "React",
  },
].reverse();
